"""add quarantine table

Revision ID: 084e3fef9cfc
Revises: 9e58483e6c32
Create Date: 2026-07-28 13:43:44.504892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084e3fef9cfc'
down_revision: Union[str, Sequence[str], None] = '9e58483e6c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quarantine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_name', sa.String(length=255), nullable=False),
    sa.Column('test_id', sa.String(length=1024), nullable=False),
    sa.Column('quarantined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_after_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('quarantined_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('suite_name', 'test_id', name='uq_quarantine_suite_test')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quarantine')
    # ### end Alembic commands ###
